In [4]:
import torch

# Print the PyTorch version
print(torch.__version__)

2.11.0+cpu


In [2]:
import torch
x = torch.tensor([1,2,3,4])
print(x)
print(x.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [3]:
X = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])
print(x)
print(X.shape)

tensor([1, 2, 3, 4])
torch.Size([3, 2])


In [5]:
# create tensors with some random values
## very important for weight initialization

x = torch.rand(2, 3) # gives random values between 0 and 1
print(x)

tensor([[0.8866, 0.1333, 0.0778],
        [0.1944, 0.2169, 0.1715]])


In [6]:
x = torch.randn(3,2) # normal distribution
print(x)

tensor([[-0.3422, -0.5065],
        [ 0.6040,  0.4722],
        [-1.3399,  0.6434]])


In [7]:
# basic tensor operations
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [9]:
A = torch.tensor([
    [1,2],
    [3,4]
])
B = torch.tensor([
    [5,6],
    [7,8]
])
C = torch.matmul(A,B)
print(C)

tensor([[19, 22],
        [43, 50]])


In [12]:
# gradient calculation
x = torch.tensor(3.0, requires_grad=True)
y = x**2 # derivative of x**2 = 2x and 2x = 2*3 = 6
y.backward() # calculates how much y changes when x changes, and
# In PyTorch, y.backward() computes the gradients of a tensor with respect to the "leaf" nodes
# (the initial inputs or model parameters) in the dynamic computation graph. This function serves
# as the core engine for automatic differentiation and backpropagation during the training of neural networks.
print(x.grad)

# requires_grad = True
# In PyTorch, requires_grad = True tells the PyTorch Autograd Engine to track all mathematical operations
# performed on a tensor so it can automatically calculate gradients during backpropagation.

tensor(6.)
